// load sdbi shared libraryssh://git@stash.six-group.net:22/sdbi/jenkins-shared-library.git
library identifier: 'sdbi-shared-lib@develop', retriever: modernSCM(
        [$class       : 'GitSCMSource',
         remote       : 'ssh://git@stash.six-group.net:22/sdbi/jenkins-shared-library.git',
         credentialsId: 'six-baseimages-bitbucket-secret'])

def jobContext = getInitialJobContext()

buildOracleJavaImages("server-jre", jobContext)
buildOracleJavaImages("jdk", jobContext)

def buildOracleJavaImages(String type, jobContext) {
    stage("Build ${type} images") {
        def versions
        def registry

        node() {
            sh 'curl --fail --silent --show-error --output jq https://artifactory.six-group.net/artifactory/generic-release/jq/1.5/jq-linux64 && chmod 755 jq'
            versions = findAvailableVersions(type)
            registry = getImageStreamRegistryUrl("oracle-java-${type}")
        }
        for (i = 0; i < versions.length; i++) {
            node() {
                openshiftBuild bldCfg: 'oracle-java-8-build', env: [[name: 'SIX_JAVA_VERSION', value: versions[i]], [name: 'SIX_JAVA_PACKAGE', value: type], [name: 'SIX_BUILD_VERSION', value: jobContext.currentBuildVersion]], showBuildLogs: 'true', verbose: 'false', waitTime: '5', waitUnit: 'min'
                openshiftTag srcStream: "oracle-java-build", srcTag: 'tmp-8', destStream: "oracle-java-${type}", destTag: versions[i]
            }
            imageMgmtNode('imageMgmt-java-8') {
                sh "skopeoCopy.sh -f ${registry}:${versions[i]} -t artifactory.six-group.net/sdbi/oracle-java-${type}-8:${versions[i]}"
                sh "promoteToArtifactory.sh -i sdbi/oracle-java-${type}-8 -t ${versions[i]} -r sdbi-docker-release-local -c"

                sh "skopeoCopy.sh -f ${registry}:${versions[i]} -t artifactory.six-group.net/sdbi/oracle-java-${type}-8:${jobContext.currentBuildVersion}"
                sh "promoteToArtifactory.sh -i sdbi/oracle-java-${type}-8 -t ${jobContext.currentBuildVersion} -r sdbi-docker-release-local -c"

                if (i == 0) {
                    sh "skopeoCopy.sh -f ${registry}:${versions[i]} -t artifactory.six-group.net/sdbi/oracle-java-${type}-8:latest"
                    sh "promoteToArtifactory.sh -i sdbi/oracle-java-${type}-8 -t latest -r sdbi-docker-release-local -c"
                }
            }
        }
    }
}


def findAvailableVersions(String type) {
    sh 'curl --fail --silent --show-error --output versions.json https://artifactory.six-group.net/artifactory/api/storage/generic-release/oracle/java/8/'
    result = sh returnStdout: true, script: "cat versions.json | ./jq -r '.children | sort_by(.uri) | reverse [] | select(.uri | contains(\"${type}\")) .uri | sub(\"${type}\"; \"\") | split(\"-\")[1]'"
    result.split("\n")
}
